### PR TITLE
Allow user to moderate content from published lists.

### PR DESCRIPTION
**Pull request by dkinzer**
Ref: https://github.com/NuCivic/healthdata/issues/437
Ref: https://github.com/NuCivic/healthdata/issues/476
Ref: https://github.com/NuCivic/healthdata/issues/482
Ref: https://github.com/NuCivic/healthdata/issues/498

Acceptance:
- [ ] Reject and publish actions available from 'workbench/content/edited'
- [ ] Reject and publish actions available from 'workbench/conent/all'
- [ ] All workbench lists use the same format.
- [ ] worbench moderation is limited to Datasets and Resources.
- [ ] Does not cause weird features override.

### CODE REVIEW

**Comment by rhabbachi** [comment]
@dkinzer At first glance, shouldn't `dkan_workflow.views_default.inc` be deleted?

**Comment by dkinzer** [comment]
@rhabbachi I don't think it matters since it's just an empty file.

**Comment by rhabbachi** [comment]
@dkinzer  [Does not look empty when opening the file](https://github.com/NuCivic/dkan_workflow/blob/96cb950246848ab53cf07d905ba30326ee049be1/dkan_workflow.views_default.inc)

**Comment by dkinzer** [comment]
:) Ugh, must have not added that to my commit.  I'll push up change plus one refactor now.

**Comment by dkinzer** [comment]
@rhabbachi OK, removed file.

**Comment by dkinzer** [comment]
Looks like the format for these views doesn't confirm to what the others are doing so I'm going to change it so that it does.

**Comment by dkinzer** [comment]
@rhabbachi I've piggy backed some additional requirements to this PR.

**Comment by rhabbachi** [comment]
@dkinzer Still looking to do a full review for this PR later, but this is some observation from reading the code and working with @SalahMessaoud.

I really like the `dkan_workflow_limit_workflow_exposed_filter_node_types()` code wise, Still I would vote that we should not use `dkan_workflow_form_alter()` for this requirement and instead re-export the views with the correct filter configuration. This will spear us and future developers working on this the "WTF why changing the filter does not affect this _@#_$ view behavior?" as happened this morning with Salah.

**Comment by dkinzer** [comment]
> "WTF why changing the filter does not affect this _@#_$ view behavior?"

hah, that's what I think pretty much about everything I do in Drupal

**Comment by dkinzer** [comment]
@SalahMessaoud @rhabbachi I couldn't find an easy way to remove the options for all the workbench views.  Solving this issue as you propose means we have to export all the views any time we wan to make that change.  And since the decision to just use workflow stuff with datasets and resources is pretty central to DKAN it makes sense to take care of it in a final sort of way.

**Comment by rhabbachi** [comment]
@dkinzer yes you are right.

Can you update the default value to reflect the "-Any-" behavior of views? By default we want to display datasets and resources.

**Comment by dkinzer** [comment]
@rhabbachi I added '- Any -' to the list.

**Comment by dkinzer** [comment]
hmm.. I should probably be translating those :/

**Comment by dkinzer** [comment]
@rhabbachi I just added a fix so that those overrides don't happen anymore while still keeping functionality.  This should make it possible for you to get this into DKAN now: https://github.com/NuCivic/healthdata/issues/498

**Pull request merged**
